### ISSUE TITLE
Looking for comment explanation

### ISSUE THREAD

**Issue by jeffleder** [Darkelf1989/PowerShell-Compliance-Scripts#1]
What are the numerical identifiers in the comments (e.g. 1.21 1198, 20.38 1462, and 28.1 3944) in reference to? Do they indicate specific compliance rules and if so, by which organization(s) and where can I find further documentation pertaining to them?

**Comment by OrganizedMayhem** [comment]
@jeffleder Sorry just seeing this now. The numbers are the control numbers in Qualys Vulnerability scanner's HIPAA/NIST compliance scans.  Finally have time to add more functions to the script. If you have any feedback let me know.

**Comment by jeffleder** [comment]
Thanks for the response!
